name: citibike
version: '1.0.0'
config-version: 2

# These configurations specify where dbt should look for different types of files.
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: ["target"] 

models:
    citibike:
        +database: citibike
        +materialized: table
